name: Upload Release Assets

on:
  release:
    types: [published, created]

jobs:
  upload-assets:
    name: Upload Tools ZIPs to Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Upload Tool ZIPs to Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/Delphi2Schema.zip
            releases/JSON2Schema.zip
            releases/Schema2DDL.zip
            releases/Schema2Delphi.zip
            releases/Schema2Doc.zip
            releases/Schema2REST.zip
            releases/SchemaBundler.zip
            releases/SchemaLinter.zip
            releases/SchemaMigrator.zip
            releases/SchemaMockGen.zip
            releases/SchemaOptimizer.zip
            releases/SchemaValidator.zip
            releases/VisualTestSuiteRunner.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
